// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';
import {apperr} from '../models';

export function ActivateDocument(arg1:bridge.Request,arg2:string,arg3:number):Promise<apperr.DocumentTransitionResult>;

export function AuthorizeKeepMine(arg1:bridge.Request,arg2:string,arg3:number,arg4:string,arg5:apperr.DiskVersion):Promise<apperr.ConflictResult>;

export function CancelConflict(arg1:bridge.Request,arg2:string,arg3:number,arg4:apperr.DiskVersion):Promise<apperr.ConflictResult>;

export function CancelNormalization(arg1:bridge.Request,arg2:string,arg3:string):Promise<apperr.ClassifiedVoidResult>;

export function CheckExternalChanges(arg1:bridge.Request,arg2:string):Promise<apperr.ConflictResult>;

export function CloseDocument(arg1:bridge.Request,arg2:string,arg3:number):Promise<apperr.TabTransitionResult>;

export function CopyPath(arg1:bridge.Request,arg2:string):Promise<apperr.PathCommandResult>;

export function ExecuteClosePlan(arg1:bridge.Request,arg2:string):Promise<apperr.TabTransitionResult>;

export function GetState(arg1:bridge.Request):Promise<apperr.StateResult>;

export function NewDocument(arg1:bridge.Request,arg2:number):Promise<apperr.DocumentTransitionResult>;

export function OpenDocument(arg1:bridge.Request,arg2:number):Promise<apperr.OpenResult>;

export function OpenPreviewLink(arg1:bridge.Request,arg2:string,arg3:string):Promise<apperr.OpenResult>;

export function OpenRecentFile(arg1:bridge.Request,arg2:string,arg3:number):Promise<apperr.OpenResult>;

export function PrepareClose(arg1:bridge.Request,arg2:string,arg3:Array<string>,arg4:number):Promise<apperr.ClosePlanResult>;

export function ReloadFromDisk(arg1:bridge.Request,arg2:string,arg3:number,arg4:apperr.DiskVersion):Promise<apperr.ConflictResult>;

export function ReopenLastFile(arg1:bridge.Request,arg2:number):Promise<apperr.OpenResult>;

export function ReorderDocument(arg1:bridge.Request,arg2:string,arg3:number,arg4:number):Promise<apperr.TabTransitionResult>;

export function ResolveClosePlan(arg1:bridge.Request,arg2:string,arg3:Array<apperr.ClosePlanDecision>):Promise<apperr.ClosePlanResult>;

export function RevealInFileManager(arg1:bridge.Request,arg2:string):Promise<apperr.PathCommandResult>;

export function Save(arg1:bridge.Request,arg2:string,arg3:number,arg4:string):Promise<apperr.WriteResult>;

export function SaveAs(arg1:bridge.Request,arg2:string,arg3:number,arg4:string):Promise<apperr.WriteResult>;

export function SetDocView(arg1:bridge.Request,arg2:string,arg3:apperr.DocViewInput):Promise<apperr.VoidResult>;

export function SetUILayout(arg1:bridge.Request,arg2:apperr.UILayout):Promise<apperr.VoidResult>;

export function SkipConflict(arg1:bridge.Request,arg2:string,arg3:number,arg4:apperr.DiskVersion):Promise<apperr.ConflictResult>;

export function UpdateBuffer(arg1:bridge.Request,arg2:string,arg3:string):Promise<apperr.VoidResult>;
