// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateDocument(arg1, arg2, arg3) {
  return window['go']['appmodel']['AppModelHandler']['ActivateDocument'](arg1, arg2, arg3);
}

export function AuthorizeKeepMine(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['appmodel']['AppModelHandler']['AuthorizeKeepMine'](arg1, arg2, arg3, arg4, arg5);
}

export function CancelConflict(arg1, arg2, arg3, arg4) {
  return window['go']['appmodel']['AppModelHandler']['CancelConflict'](arg1, arg2, arg3, arg4);
}

export function CancelNormalization(arg1, arg2, arg3) {
  return window['go']['appmodel']['AppModelHandler']['CancelNormalization'](arg1, arg2, arg3);
}

export function CheckExternalChanges(arg1, arg2) {
  return window['go']['appmodel']['AppModelHandler']['CheckExternalChanges'](arg1, arg2);
}

export function ChooseWorkspaceFolder(arg1) {
  return window['go']['appmodel']['AppModelHandler']['ChooseWorkspaceFolder'](arg1);
}

export function ClassifyDroppedPaths(arg1, arg2) {
  return window['go']['appmodel']['AppModelHandler']['ClassifyDroppedPaths'](arg1, arg2);
}

export function ClearRecentItems(arg1) {
  return window['go']['appmodel']['AppModelHandler']['ClearRecentItems'](arg1);
}

export function CloseDocument(arg1, arg2, arg3) {
  return window['go']['appmodel']['AppModelHandler']['CloseDocument'](arg1, arg2, arg3);
}

export function CloseWorkspace(arg1) {
  return window['go']['appmodel']['AppModelHandler']['CloseWorkspace'](arg1);
}

export function CopyPath(arg1, arg2) {
  return window['go']['appmodel']['AppModelHandler']['CopyPath'](arg1, arg2);
}

export function CopyWorkspacePath(arg1, arg2) {
  return window['go']['appmodel']['AppModelHandler']['CopyWorkspacePath'](arg1, arg2);
}

export function CreateWorkspaceFile(arg1, arg2, arg3) {
  return window['go']['appmodel']['AppModelHandler']['CreateWorkspaceFile'](arg1, arg2, arg3);
}

export function CreateWorkspaceFolder(arg1, arg2, arg3) {
  return window['go']['appmodel']['AppModelHandler']['CreateWorkspaceFolder'](arg1, arg2, arg3);
}

export function ExecuteClosePlan(arg1, arg2) {
  return window['go']['appmodel']['AppModelHandler']['ExecuteClosePlan'](arg1, arg2);
}

export function GetState(arg1) {
  return window['go']['appmodel']['AppModelHandler']['GetState'](arg1);
}

export function NewDocument(arg1, arg2) {
  return window['go']['appmodel']['AppModelHandler']['NewDocument'](arg1, arg2);
}

export function OpenDocument(arg1, arg2) {
  return window['go']['appmodel']['AppModelHandler']['OpenDocument'](arg1, arg2);
}

export function OpenPreviewLink(arg1, arg2, arg3) {
  return window['go']['appmodel']['AppModelHandler']['OpenPreviewLink'](arg1, arg2, arg3);
}

export function OpenRecentFile(arg1, arg2, arg3) {
  return window['go']['appmodel']['AppModelHandler']['OpenRecentFile'](arg1, arg2, arg3);
}

export function OpenWorkspace(arg1, arg2) {
  return window['go']['appmodel']['AppModelHandler']['OpenWorkspace'](arg1, arg2);
}

export function PrepareClose(arg1, arg2, arg3, arg4) {
  return window['go']['appmodel']['AppModelHandler']['PrepareClose'](arg1, arg2, arg3, arg4);
}

export function RefreshRecentItems(arg1) {
  return window['go']['appmodel']['AppModelHandler']['RefreshRecentItems'](arg1);
}

export function RefreshWorkspace(arg1) {
  return window['go']['appmodel']['AppModelHandler']['RefreshWorkspace'](arg1);
}

export function ReloadFromDisk(arg1, arg2, arg3, arg4) {
  return window['go']['appmodel']['AppModelHandler']['ReloadFromDisk'](arg1, arg2, arg3, arg4);
}

export function ReopenLastFile(arg1, arg2) {
  return window['go']['appmodel']['AppModelHandler']['ReopenLastFile'](arg1, arg2);
}

export function ReorderDocument(arg1, arg2, arg3, arg4) {
  return window['go']['appmodel']['AppModelHandler']['ReorderDocument'](arg1, arg2, arg3, arg4);
}

export function ResolveClosePlan(arg1, arg2, arg3) {
  return window['go']['appmodel']['AppModelHandler']['ResolveClosePlan'](arg1, arg2, arg3);
}

export function RevealInFileManager(arg1, arg2) {
  return window['go']['appmodel']['AppModelHandler']['RevealInFileManager'](arg1, arg2);
}

export function RevealWorkspacePath(arg1, arg2) {
  return window['go']['appmodel']['AppModelHandler']['RevealWorkspacePath'](arg1, arg2);
}

export function Save(arg1, arg2, arg3, arg4) {
  return window['go']['appmodel']['AppModelHandler']['Save'](arg1, arg2, arg3, arg4);
}

export function SaveAs(arg1, arg2, arg3, arg4) {
  return window['go']['appmodel']['AppModelHandler']['SaveAs'](arg1, arg2, arg3, arg4);
}

export function SetDocView(arg1, arg2, arg3) {
  return window['go']['appmodel']['AppModelHandler']['SetDocView'](arg1, arg2, arg3);
}

export function SetUILayout(arg1, arg2) {
  return window['go']['appmodel']['AppModelHandler']['SetUILayout'](arg1, arg2);
}

export function SetWorkspaceHiddenFolders(arg1, arg2) {
  return window['go']['appmodel']['AppModelHandler']['SetWorkspaceHiddenFolders'](arg1, arg2);
}

export function SkipConflict(arg1, arg2, arg3, arg4) {
  return window['go']['appmodel']['AppModelHandler']['SkipConflict'](arg1, arg2, arg3, arg4);
}

export function UpdateBuffer(arg1, arg2, arg3) {
  return window['go']['appmodel']['AppModelHandler']['UpdateBuffer'](arg1, arg2, arg3);
}
