// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apperr} from '../models';

export function ActivateDocument(arg1:string,arg2:number):Promise<apperr.DocumentTransitionResult>;

export function AuthorizeKeepMine(arg1:string,arg2:number,arg3:string,arg4:apperr.DiskVersion):Promise<apperr.ConflictResult>;

export function CancelConflict(arg1:string,arg2:number,arg3:apperr.DiskVersion):Promise<apperr.ConflictResult>;

export function CheckExternalChanges(arg1:string):Promise<apperr.ConflictResult>;

export function CloseDocument(arg1:string,arg2:number):Promise<apperr.TabTransitionResult>;

export function CopyPath(arg1:string):Promise<apperr.PathCommandResult>;

export function ExecuteClosePlan(arg1:string):Promise<apperr.TabTransitionResult>;

export function GetState():Promise<apperr.StateResult>;

export function NewDocument(arg1:number):Promise<apperr.DocumentTransitionResult>;

export function OpenDocument(arg1:number):Promise<apperr.OpenResult>;

export function PrepareClose(arg1:apperr.ClosePlanKind,arg2:Array<string>,arg3:number):Promise<apperr.ClosePlanResult>;

export function ReloadFromDisk(arg1:string,arg2:number,arg3:apperr.DiskVersion):Promise<apperr.ConflictResult>;

export function ReorderDocument(arg1:string,arg2:number,arg3:number):Promise<apperr.TabTransitionResult>;

export function ResolveClosePlan(arg1:string,arg2:Array<apperr.ClosePlanDecision>):Promise<apperr.ClosePlanResult>;

export function RevealInFileManager(arg1:string):Promise<apperr.PathCommandResult>;

export function Save(arg1:string,arg2:number,arg3:string):Promise<apperr.WriteResult>;

export function SaveAs(arg1:string,arg2:number,arg3:string):Promise<apperr.WriteResult>;

export function SetDocView(arg1:string,arg2:apperr.DocViewInput):Promise<apperr.VoidResult>;

export function SetUILayout(arg1:apperr.UILayout):Promise<apperr.VoidResult>;

export function SkipConflict(arg1:string,arg2:number,arg3:apperr.DiskVersion):Promise<apperr.ConflictResult>;

export function UpdateBuffer(arg1:string,arg2:string):Promise<apperr.VoidResult>;
