// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateDocument(arg1, arg2) {
  return window['go']['appmodel']['AppModelHandler']['ActivateDocument'](arg1, arg2);
}

export function CloseDocument(arg1, arg2) {
  return window['go']['appmodel']['AppModelHandler']['CloseDocument'](arg1, arg2);
}

export function CopyPath(arg1) {
  return window['go']['appmodel']['AppModelHandler']['CopyPath'](arg1);
}

export function GetState() {
  return window['go']['appmodel']['AppModelHandler']['GetState']();
}

export function NewDocument(arg1) {
  return window['go']['appmodel']['AppModelHandler']['NewDocument'](arg1);
}

export function OpenDocument(arg1) {
  return window['go']['appmodel']['AppModelHandler']['OpenDocument'](arg1);
}

export function ReorderDocument(arg1, arg2, arg3) {
  return window['go']['appmodel']['AppModelHandler']['ReorderDocument'](arg1, arg2, arg3);
}

export function RevealInFileManager(arg1) {
  return window['go']['appmodel']['AppModelHandler']['RevealInFileManager'](arg1);
}

export function Save(arg1, arg2, arg3) {
  return window['go']['appmodel']['AppModelHandler']['Save'](arg1, arg2, arg3);
}

export function SaveAs(arg1, arg2, arg3) {
  return window['go']['appmodel']['AppModelHandler']['SaveAs'](arg1, arg2, arg3);
}

export function SetDocView(arg1, arg2) {
  return window['go']['appmodel']['AppModelHandler']['SetDocView'](arg1, arg2);
}

export function SetUILayout(arg1) {
  return window['go']['appmodel']['AppModelHandler']['SetUILayout'](arg1);
}

export function UpdateBuffer(arg1, arg2) {
  return window['go']['appmodel']['AppModelHandler']['UpdateBuffer'](arg1, arg2);
}
