// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package store

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT key, value, type
FROM settings
WHERE key = ?1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var i Setting
	err := row.Scan(&i.Key, &i.Value, &i.Type)
	return i, err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (key, value, type)
VALUES (?1, ?2, ?3)
ON CONFLICT(key) DO UPDATE SET
    value = excluded.value,
    type = excluded.type
`

type UpsertSettingParams struct {
	Key   string
	Value string
	Type  string
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value, arg.Type)
	return err
}
