#!/usr/bin/env python3
"""Find what an existing Delivery Spec tree is missing relative to the current revision.

    python3 upgrade_check.py docs/delivery
    python3 upgrade_check.py docs/delivery --repo . --json

A tree generated by an earlier revision of this skill is not wrong — it is incomplete in
specific, known ways. This reports exactly those, so an upgrade is a short list of targeted
edits rather than a regeneration that churns thousands of lines and loses the answers the
user gave along the way.

Each finding names the revision that introduced the requirement and what to do about it.
Nothing is fixed automatically: several of these need a decision.
"""

import argparse
import json
import re
import sys
from pathlib import Path

CURRENT_REVISION = 2

LEGACY_IDS = re.compile(r"\b(?:FR|REQ|NFR|EC|DD|SPEC|AC|UC|SC|TC|BR)-[A-Z0-9]{1,10}(?:-\d+)?\b")
LEGACY_PATH = re.compile(r"`?\b\d{2}_[A-Za-z][A-Za-z_]*/[A-Za-z0-9_.-]+\.md\b`?")
BARE_ANCHOR_BULLET = re.compile(r"^\s*[-*]\s*`[^`]+#[a-z0-9-]+`\s*$", re.M)
ANY_BULLET = re.compile(r"^\s*[-*]\s+\S", re.M)


class Finding:
    def __init__(self, rev, severity, what, where, fix):
        self.rev, self.severity, self.what, self.where, self.fix = rev, severity, what, where, fix

    def as_dict(self):
        return {"revision": self.rev, "severity": self.severity, "finding": self.what,
                "where": self.where, "fix": self.fix}


def read(p: Path) -> str:
    try:
        return p.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def detect_revision(spec_root: Path) -> int:
    marker = spec_root / ".delivery-spec"
    if marker.is_file():
        m = re.search(r"revision:\s*(\d+)", read(marker))
        if m:
            return int(m.group(1))
    return 1


def check(spec_root: Path, repo: Path) -> list:
    f = []
    add = lambda *a: f.append(Finding(*a))

    # ---------------------------------------------------------------- r2: workflow
    if not (spec_root / "WORKFLOW.md").is_file():
        add(2, "error", "No WORKFLOW.md — nothing tells a reader which command to run when, "
                        "what it produces, or what to do with the output.",
            str(spec_root / "WORKFLOW.md"),
            "Generate it from the skill's assets/templates/workflow.md with this project's "
            "real command names substituted.")

    # ---------------------------------------------------------------- r2: release home
    arch = spec_root / "architecture"
    if arch.is_dir() and not (arch / "release.md").is_file():
        pack = [p for p in repo.rglob("*")
                if p.is_file() and p.name in
                {"goreleaser.yml", "goreleaser.yaml", ".goreleaser.yml", "Dockerfile",
                 "wails.json", "electron-builder.yml", "pyproject.toml", "setup.py"}]
        sev = "error" if pack else "warning"
        add(2, sev, "No architecture/release.md — how the software is built, packaged, "
                    "signed and shipped has no normative home, so it ends up archived or "
                    "scattered.",
            str(arch / "release.md"),
            "Create it. Artifact matrix, target platforms, packaging, signing, versioning, "
            "the release pipeline, and what CI runs."
            + (f" This repo has {pack[0].name}, so the material exists." if pack else ""))

    # ---------------------------------------------------------------- r2: stub status
    work = spec_root / "work"
    if work.is_dir():
        for story in sorted(work.glob("story-*.md")):
            text = read(story)
            has_status = re.search(r"^\*\*STATUS:\*\*", text, re.M)
            expanded = "## Technical constraints" in text
            if not has_status:
                add(2, "error" if not expanded else "warning",
                    "Story carries no `**STATUS:**` line, so nothing can tell a stub from a "
                    "planned story — /build-story cannot refuse it.",
                    str(story),
                    "Add `**STATUS:** stub — not buildable. Run `/plan-story NNN` to expand.` "
                    "or `**STATUS:** planned — ready to build.` as the second line.")

            sec = re.search(r"^## Rules this story owns\s*$(.*?)(?:^## |\Z)", text, re.M | re.S)
            if sec:
                bare = len(BARE_ANCHOR_BULLET.findall(sec.group(1)))
                total = len(ANY_BULLET.findall(sec.group(1)))
                if total and bare / total > 0.5:
                    add(2, "error",
                        f"Story stub is a bare anchor list ({bare} of {total} bullets are an "
                        f"anchor with no prose). Neither a person nor an agent can judge the "
                        f"slicing, or see how big the story really is.",
                        str(story),
                        "Give every bullet a rule title and one sentence saying what it "
                        "actually requires, with its real values.")

            owned = re.search(r"^## What must be true when this is done\s*$(.*?)^## ",
                              text, re.M | re.S)
            if owned:
                n = len(re.findall(r"^###\s", owned.group(1), re.M))
                if n > 5:
                    add(2, "warning",
                        f"Story owns {n} rules (ceiling is 5). An oversized story is built as "
                        f"most-of-a-story, and nothing downstream counts rules.",
                        str(story), "Split it, or accept it explicitly and say why.")

    # ---------------------------------------------------------------- r2: baselines
    bdir = work / "baselines" if work.is_dir() else None
    if bdir and bdir.is_dir():
        for b in sorted(bdir.glob("*.md")):
            text = read(b)
            if not re.search(r"\bexit\b", text, re.I):
                add(2, "error",
                    "Baseline records no gate exit codes. A gate that crashed and a gate that "
                    "found nothing look identical, so the verify diff passes unconditionally.",
                    str(b),
                    "Regenerate the baseline with the r2 baseline script, which records an "
                    "exit code per gate and marks a non-zero exit with zero findings "
                    "UNRELIABLE.")
                break
            if re.search(r"findings at baseline \(0\)", text) and \
               re.search(r"exit\D{0,12}[1-9]", text, re.I):
                add(2, "error",
                    "Baseline records a non-zero gate exit alongside zero findings — that "
                    "gate analysed nothing, and every story verified against it passed "
                    "without being checked.",
                    str(b),
                    "Fix the gate, log it in plan/KNOWN_ISSUES.md, re-baseline, and re-verify "
                    "any story built on it.")

    # ---------------------------------------------------------------- r2: scripts
    for name, needle, why in (
        ("baseline", "UNRELIABLE",
         "does not classify a gate that exited non-zero with no findings"),
        ("verify", "UNRELIABLE",
         "does not refuse an unreliable baseline, so an empty-vs-empty diff prints PASS"),
    ):
        hits = [p for p in repo.rglob(f"*{name}*.sh") if ".git" not in p.parts]
        for p in hits:
            if needle not in read(p):
                add(2, "error", f"`{p.name}` {why}.", str(p),
                    f"Regenerate from the skill's assets/scripts/{name}.sh.")

    # ---------------------------------------------------------------- r2: commands
    cmd_dir = repo / ".claude" / "commands"
    if cmd_dir.is_dir():
        for name in ("plan-phase", "plan-story", "build-story", "finish-phase", "reconcile"):
            p = cmd_dir / f"{name}.md"
            if not p.is_file():
                add(2, "warning", f"`/{name}` is missing.", str(p),
                    "Regenerate from the skill's assets/commands/.")
                continue
            text = read(p)
            if "**Next:**" not in text:
                add(2, "error",
                    f"`/{name}` never tells the user what to run next, so the workflow has to "
                    f"be remembered rather than followed.",
                    str(p), "Add the closing `> **Next:** …` block from the r2 template.")
            if name == "plan-story":
                if "in place" not in text:
                    add(2, "error",
                        "/plan-story does not open the stub or expand it in place, so an "
                        "agent asked for story 059 can silently expand a different story.",
                        str(p), "Regenerate from the r2 template (step 0).")
                if "check_story" not in text:
                    add(2, "error",
                        "/plan-story has no mechanical copy-fidelity check, so a rule copied "
                        "with rows missing reaches the implementer unnoticed.",
                        str(p), "Regenerate from the r2 template (steps 3 and 5).")
            if name == "plan-phase" and "STATUS:" not in text:
                add(2, "error",
                    "/plan-phase writes stubs with no status marker and no prose requirement, "
                    "which is what produces bare anchor lists.",
                    str(p), "Regenerate from the r2 template (step 4).")
            if name == "build-story" and "0." not in text.split("\n#")[0] + text:
                pass
            if name == "build-story":
                if "stub" not in text:
                    add(2, "error",
                        "/build-story does not refuse a stub, so it can be asked to invent "
                        "the missing half of a story with nobody reviewing it.",
                        str(p), "Regenerate from the r2 template (step 0).")
                if "UNRELIABLE" not in text and "did not run" not in text:
                    add(2, "error",
                        "/build-story treats a broken baseline as a note rather than a hard "
                        "stop.", str(p), "Regenerate from the r2 template (step 1a).")
    else:
        add(2, "warning", "No .claude/commands/ — the workflow commands were never generated.",
            str(cmd_dir), "Run the skill's Step 5.")

    # ---------------------------------------------------------------- r2: AGENTS.md
    agents = repo / "AGENTS.md"
    if agents.is_file():
        text = read(agents)
        for needle, what, fix in (
            ("no-verify", "the `--no-verify` prohibition is missing",
             "Add: never bypass a commit hook with `--no-verify`."),
            ("failing test", "the 'never delete a failing test' prohibition is missing",
             "Add: never delete, skip or ignore a failing test to get a gate green."),
            ("WORKFLOW", "AGENTS.md does not point at WORKFLOW.md",
             "Add the workflow table and a pointer, so an agent mid-session knows what runs next."),
        ):
            if needle.lower() not in text.lower():
                add(2, "error", what, str(agents), fix)
    else:
        add(2, "warning", "No AGENTS.md at the repo root.", str(agents),
            "Generate it from the skill's assets/templates/AGENTS.md.")

    # ---------------------------------------------------------------- r2: leftover IDs
    for sub, label in (("adr", "ADRs"), ("work", "stories")):
        d = spec_root / sub
        if not d.is_dir():
            continue
        total = 0
        files = 0
        for p in d.rglob("*.md"):
            n = len(LEGACY_IDS.findall(read(p)))
            if n:
                total += n
                files += 1
        if total:
            add(2, "error",
                f"{total} legacy numeric identifier(s) survive across {files} {label}. A "
                f"conversion that rewrote spec/ but not these leaves two vocabularies in the "
                f"repository, and grep finds the dead one.",
                str(d),
                "Rewrite them to `file.md#anchor` form, or — for genuinely historical ADRs — "
                "add a one-line header saying the identifiers are historical and naming the "
                "mapping.")

    # ---------------------------------------------------------------- r2: dead paths
    dead = {}
    for p in spec_root.rglob("*.md"):
        if "_archive" in str(p):
            continue
        hits = LEGACY_PATH.findall(read(p))
        if hits:
            dead[str(p.relative_to(spec_root))] = len(hits)
    if dead:
        total = sum(dead.values())
        add(2, "error",
            f"{total} reference(s) to pre-conversion paths (`NN_Directory/FILE.md`) across "
            f"{len(dead)} file(s). They resolve nowhere.",
            ", ".join(sorted(dead)[:5]) + (" …" if len(dead) > 5 else ""),
            "Rewrite each to its new path, or delete the sentence if the content moved into "
            "the rule itself.")

    # ---------------------------------------------------------------- r2: archive link
    archives = [d for d in (repo / "docs").glob("_archive-*") if d.is_dir()] \
        if (repo / "docs").is_dir() else []
    if archives:
        readme = read(spec_root / "README.md")
        if not any(a.name in readme for a in archives):
            add(2, "warning",
                "An archive of the pre-conversion specification exists but nothing in the "
                "live tree points at it, so it is unreachable by reading and misleading by "
                "grep.",
                ", ".join(a.name for a in archives),
                "Add a line to README.md naming the archive, its date, and that it is "
                "historical and not normative.")
        for a in archives:
            empty = [d for d in a.rglob("*") if d.is_dir() and not any(d.iterdir())]
            if empty:
                add(2, "warning",
                    f"The archive has {len(empty)} empty directory/ies, and its index may "
                    f"point at content that is not there.",
                    ", ".join(str(d.relative_to(a)) for d in empty[:5]),
                    "Either restore the content or remove the directory and its index entry.")

    # ---------------------------------------------------------------- r2: boilerplate
    if (spec_root / "spec").is_dir():
        oq = {}
        for p in (spec_root / "spec").rglob("*.md"):
            m = re.search(r"^## Open questions\s*$(.*?)(?:^## |\Z)", read(p), re.M | re.S)
            if m:
                body = " ".join(m.group(1).split())
                if body:
                    oq.setdefault(body, []).append(p.name)
        for body, files in oq.items():
            if len(files) >= 3:
                add(2, "warning",
                    f"{len(files)} feature files share an identical `## Open questions` "
                    f"body — that is boilerplate, not thinking, and it passes every "
                    f"mechanical check.",
                    ", ".join(sorted(files)[:6]) + (" …" if len(files) > 6 else ""),
                    "Empty the section where there is genuinely no open question. An empty "
                    "section is a statement; a copied sentence is noise.")

    return f


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("spec_root", help="e.g. docs/delivery")
    ap.add_argument("--repo", default=None, help="repository root (default: spec_root/../..)")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()

    spec_root = Path(args.spec_root).resolve()
    if not spec_root.is_dir():
        print(f"error: {spec_root} is not a directory", file=sys.stderr)
        return 2
    repo = Path(args.repo).resolve() if args.repo else spec_root.parent.parent

    found = detect_revision(spec_root)
    findings = check(spec_root, repo)

    if args.json:
        print(json.dumps({"found_revision": found, "current_revision": CURRENT_REVISION,
                          "findings": [f.as_dict() for f in findings]}, indent=2))
        return 1 if any(f.severity == "error" for f in findings) else 0

    print(f"upgrade_check — {spec_root}")
    print(f"tree revision: r{found}   ·   current: r{CURRENT_REVISION}\n")
    if not findings:
        print("  Nothing to upgrade. The tree already meets the current revision.")
        print(f"\n  Write `revision: {CURRENT_REVISION}` into {spec_root}/.delivery-spec")
        return 0

    errors = [f for f in findings if f.severity == "error"]
    warns = [f for f in findings if f.severity != "error"]
    for group, label in ((errors, "ERROR"), (warns, "warning")):
        for f in group:
            print(f"  [{label}] (r{f.rev}) {f.what}")
            print(f"           where: {f.where}")
            print(f"           fix:   {f.fix}\n")

    print(f"{len(errors)} error(s), {len(warns)} warning(s)")
    print("\nFix these, then write `revision: "
          f"{CURRENT_REVISION}` into {spec_root}/.delivery-spec")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
