// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthorizeQuit(arg1, arg2) {
  return window['go']['application']['ApplicationHandler']['AuthorizeQuit'](arg1, arg2);
}

export function CancelQuit(arg1, arg2) {
  return window['go']['application']['ApplicationHandler']['CancelQuit'](arg1, arg2);
}

export function RetryStartup(arg1) {
  return window['go']['application']['ApplicationHandler']['RetryStartup'](arg1);
}

export function WindowReady(arg1) {
  return window['go']['application']['ApplicationHandler']['WindowReady'](arg1);
}
