// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RetryStartup() {
  return window['go']['application']['ApplicationHandler']['RetryStartup']();
}

export function WindowReady() {
  return window['go']['application']['ApplicationHandler']['WindowReady']();
}
