// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apperr} from '../models';

export function RetryStartup():Promise<apperr.VoidResult>;

export function WindowReady():Promise<apperr.VoidResult>;
