// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';
import {apperr} from '../models';

export function AuthorizeQuit(arg1:bridge.Request,arg2:string):Promise<apperr.ClassifiedVoidResult>;

export function CancelQuit(arg1:bridge.Request,arg2:string):Promise<apperr.ClassifiedVoidResult>;

export function RetryStartup(arg1:bridge.Request):Promise<apperr.VoidResult>;

export function WindowReady(arg1:bridge.Request):Promise<apperr.VoidResult>;
