import type { Schema } from 'hast-util-sanitize';
import { defaultSchema } from 'rehype-sanitize';

import { withSourceLineAttributes } from './sourceLines';

/** The preview's single allowlist, shared by all Markdown standards. */
export const sanitizeSchema: Schema = {
    ...defaultSchema,
    // remark-rehype has already prefixed generated footnote ids and links.
    clobberPrefix: '',
    attributes: withSourceLineAttributes({
        ...defaultSchema.attributes,
        img: ['alt', 'src'],
    }),
    // The existing link policy needs to see file: to refuse it visibly.
    protocols: {
        ...defaultSchema.protocols,
        href: [...(defaultSchema.protocols?.href ?? []), 'file'],
    },
    strip: [
        'script',
        'style',
        'iframe',
        'object',
        'embed',
        'form',
        'noscript',
        'template',
        'textarea',
        'select',
        'button',
        'svg',
        'math',
        'title',
        'head',
        'frame',
        'applet',
        'link',
        'meta',
        'base',
        'audio',
        'video',
        'canvas',
        'noembed',
        'noframes',
        'xmp',
        'plaintext',
        'dialog',
        'portal',
    ],
    tagNames: [
        'p',
        'h1',
        'h2',
        'h3',
        'h4',
        'h5',
        'h6',
        'blockquote',
        'ul',
        'ol',
        'li',
        'pre',
        'code',
        'em',
        'strong',
        'hr',
        'table',
        'thead',
        'tbody',
        'tr',
        'th',
        'td',
        'input',
        'section',
        'details',
        'summary',
        'kbd',
        'sub',
        'sup',
        'mark',
        'ins',
        'del',
        'br',
        'abbr',
        'img',
        'a',
    ],
};
