// Generated by scripts/generate-editor-themes.mjs. Do not edit.
export const generatedEditorThemes = {
  'gme-glass-light': {
    base: 'vs',
    inherit: true,
    colors: {
      'editor.background': '#ffffff6b',
      'editor.foreground': '#1c2338',
      'editorLineNumber.foreground': '#c9ccd3',
      'editorLineNumber.activeForeground': '#1c2338',
      'editorCursor.foreground': '#5b7cff',
      'editor.selectionBackground': '#3056d333',
      'editor.selectionHighlightBackground': '#3056d333',
      'editor.lineHighlightBackground': '#46548c1f',
      'editorGutter.background': '#ffffff6b',
      'editorWidget.background': '#ffffff57',
      'editorWidget.border': '#46548c3d',
      'editorSuggestWidget.background': '#ffffff57',
      'editorSuggestWidget.foreground': '#1c2338',
      'editorSuggestWidget.selectedBackground': '#5b7cff24',
      'minimap.background': '#ffffff6b',
      'scrollbarSlider.background': '#0000002e',
      'scrollbarSlider.hoverBackground': '#0000004d',
      'editorError.foreground': '#c0324b',
      'editorWarning.foreground': '#b7791f',
    },
    rules: [
      {
        token: 'keyword.md',
        foreground: '#3056d3',
      },
      {
        token: 'keyword.md.*',
        foreground: '#3056d3',
      },
      {
        token: 'meta.separator.md',
        foreground: '#9aa1ab',
      },
      {
        token: 'keyword.table.md.*',
        foreground: '#9aa1ab',
      },
      {
        token: 'strong.md',
        foreground: '#b45309',
      },
      {
        token: 'strong.md.*',
        foreground: '#b45309',
      },
      {
        token: 'emphasis.md',
        foreground: '#7c3aed',
      },
      {
        token: 'emphasis.md.*',
        foreground: '#7c3aed',
      },
      {
        token: 'comment.md',
        foreground: '#0369a1',
      },
      {
        token: 'comment.md.*',
        foreground: '#0369a1',
      },
      {
        token: 'string.link.md',
        foreground: '#be123c',
      },
      {
        token: 'string.target.md',
        foreground: '#be123c',
      },
      {
        token: 'string.md',
        foreground: '#9aa1ab',
      },
      {
        token: 'variable.source.md',
        foreground: '#30343b',
      },
      {
        token: 'keyword.go',
        foreground: '#7c3aed',
      },
      {
        token: 'keyword.go.*',
        foreground: '#7c3aed',
      },
      {
        token: 'string.go',
        foreground: '#0369a1',
      },
      {
        token: 'comment.go',
        foreground: '#9aa1ab',
      },
      {
        token: 'comment.go.*',
        foreground: '#9aa1ab',
      },
      {
        token: 'number.go',
        foreground: '#b45309',
      },
      {
        token: 'number.go.*',
        foreground: '#b45309',
      },
      {
        token: 'delimiter.go',
        foreground: '#5c5c69',
      },
      {
        token: 'delimiter.go.*',
        foreground: '#5c5c69',
      },
      {
        token: 'annotation.go',
        foreground: '#be123c',
      },
      {
        token: 'identifier.go',
        foreground: '#3056d3',
      },
      {
        token: 'keyword.type.go',
        foreground: '#0f766e',
      },
      {
        token: 'keyword.const.go',
        foreground: '#0f766e',
      },
    ],
  },
  'gme-glass-dark': {
    base: 'vs-dark',
    inherit: true,
    colors: {
      'editor.background': '#ffffff1a',
      'editor.foreground': '#eaf0ff',
      'editorLineNumber.foreground': '#ffffff38',
      'editorLineNumber.activeForeground': '#eaf0ff',
      'editorCursor.foreground': '#7aa2ff',
      'editor.selectionBackground': '#8fb4ff42',
      'editor.selectionHighlightBackground': '#8fb4ff42',
      'editor.lineHighlightBackground': '#ffffff29',
      'editorGutter.background': '#ffffff1a',
      'editorWidget.background': '#ffffff1a',
      'editorWidget.border': '#ffffff2e',
      'editorSuggestWidget.background': '#ffffff1a',
      'editorSuggestWidget.foreground': '#eaf0ff',
      'editorSuggestWidget.selectedBackground': '#7aa2ff29',
      'minimap.background': '#ffffff1a',
      'scrollbarSlider.background': '#ffffff33',
      'scrollbarSlider.hoverBackground': '#ffffff57',
      'editorError.foreground': '#ff7a90',
      'editorWarning.foreground': '#ffcf6b',
    },
    rules: [
      {
        token: 'keyword.md',
        foreground: '#8fb4ff',
      },
      {
        token: 'keyword.md.*',
        foreground: '#8fb4ff',
      },
      {
        token: 'meta.separator.md',
        foreground: '#8a93b8',
      },
      {
        token: 'keyword.table.md.*',
        foreground: '#8a93b8',
      },
      {
        token: 'strong.md',
        foreground: '#ffd479',
      },
      {
        token: 'strong.md.*',
        foreground: '#ffd479',
      },
      {
        token: 'emphasis.md',
        foreground: '#c58bff',
      },
      {
        token: 'emphasis.md.*',
        foreground: '#c58bff',
      },
      {
        token: 'comment.md',
        foreground: '#7fe3b5',
      },
      {
        token: 'comment.md.*',
        foreground: '#7fe3b5',
      },
      {
        token: 'string.link.md',
        foreground: '#ff9d7a',
      },
      {
        token: 'string.target.md',
        foreground: '#ff9d7a',
      },
      {
        token: 'string.md',
        foreground: '#8a93b8',
      },
      {
        token: 'variable.source.md',
        foreground: '#dfe6ff',
      },
      {
        token: 'keyword.go',
        foreground: '#c58bff',
      },
      {
        token: 'keyword.go.*',
        foreground: '#c58bff',
      },
      {
        token: 'string.go',
        foreground: '#7fe3b5',
      },
      {
        token: 'comment.go',
        foreground: '#8a93b8',
      },
      {
        token: 'comment.go.*',
        foreground: '#8a93b8',
      },
      {
        token: 'number.go',
        foreground: '#ffd479',
      },
      {
        token: 'number.go.*',
        foreground: '#ffd479',
      },
      {
        token: 'delimiter.go',
        foreground: '#9aa1ab',
      },
      {
        token: 'delimiter.go.*',
        foreground: '#9aa1ab',
      },
      {
        token: 'annotation.go',
        foreground: '#ff9d7a',
      },
      {
        token: 'identifier.go',
        foreground: '#8fb4ff',
      },
      {
        token: 'keyword.type.go',
        foreground: '#5eead4',
      },
      {
        token: 'keyword.const.go',
        foreground: '#5eead4',
      },
    ],
  },
  'gme-material-light': {
    base: 'vs',
    inherit: true,
    colors: {
      'editor.background': '#faf8ff',
      'editor.foreground': '#1b1b22',
      'editorLineNumber.foreground': '#c9ccd3',
      'editorLineNumber.activeForeground': '#1b1b22',
      'editorCursor.foreground': '#4f6bed',
      'editor.selectionBackground': '#3056d333',
      'editor.selectionHighlightBackground': '#3056d333',
      'editor.lineHighlightBackground': '#eceaf6',
      'editorGutter.background': '#faf8ff',
      'editorWidget.background': '#ffffff',
      'editorWidget.border': '#e3e1ee',
      'editorSuggestWidget.background': '#ffffff',
      'editorSuggestWidget.foreground': '#1b1b22',
      'editorSuggestWidget.selectedBackground': '#dfe4ff',
      'minimap.background': '#faf8ff',
      'scrollbarSlider.background': '#0000002e',
      'scrollbarSlider.hoverBackground': '#0000004d',
      'editorError.foreground': '#b3261e',
      'editorWarning.foreground': '#8a5a00',
    },
    rules: [
      {
        token: 'keyword.md',
        foreground: '#3056d3',
      },
      {
        token: 'keyword.md.*',
        foreground: '#3056d3',
      },
      {
        token: 'meta.separator.md',
        foreground: '#9aa1ab',
      },
      {
        token: 'keyword.table.md.*',
        foreground: '#9aa1ab',
      },
      {
        token: 'strong.md',
        foreground: '#b45309',
      },
      {
        token: 'strong.md.*',
        foreground: '#b45309',
      },
      {
        token: 'emphasis.md',
        foreground: '#7c3aed',
      },
      {
        token: 'emphasis.md.*',
        foreground: '#7c3aed',
      },
      {
        token: 'comment.md',
        foreground: '#0369a1',
      },
      {
        token: 'comment.md.*',
        foreground: '#0369a1',
      },
      {
        token: 'string.link.md',
        foreground: '#be123c',
      },
      {
        token: 'string.target.md',
        foreground: '#be123c',
      },
      {
        token: 'string.md',
        foreground: '#9aa1ab',
      },
      {
        token: 'variable.source.md',
        foreground: '#30343b',
      },
      {
        token: 'keyword.go',
        foreground: '#7c3aed',
      },
      {
        token: 'keyword.go.*',
        foreground: '#7c3aed',
      },
      {
        token: 'string.go',
        foreground: '#0369a1',
      },
      {
        token: 'comment.go',
        foreground: '#9aa1ab',
      },
      {
        token: 'comment.go.*',
        foreground: '#9aa1ab',
      },
      {
        token: 'number.go',
        foreground: '#b45309',
      },
      {
        token: 'number.go.*',
        foreground: '#b45309',
      },
      {
        token: 'delimiter.go',
        foreground: '#5c5c69',
      },
      {
        token: 'delimiter.go.*',
        foreground: '#5c5c69',
      },
      {
        token: 'annotation.go',
        foreground: '#be123c',
      },
      {
        token: 'identifier.go',
        foreground: '#3056d3',
      },
      {
        token: 'keyword.type.go',
        foreground: '#0f766e',
      },
      {
        token: 'keyword.const.go',
        foreground: '#0f766e',
      },
    ],
  },
  'gme-material-dark': {
    base: 'vs-dark',
    inherit: true,
    colors: {
      'editor.background': '#16161c',
      'editor.foreground': '#e6e6ee',
      'editorLineNumber.foreground': '#ffffff38',
      'editorLineNumber.activeForeground': '#e6e6ee',
      'editorCursor.foreground': '#b3c2ff',
      'editor.selectionBackground': '#8fb4ff42',
      'editor.selectionHighlightBackground': '#8fb4ff42',
      'editor.lineHighlightBackground': '#2a2a34',
      'editorGutter.background': '#16161c',
      'editorWidget.background': '#1d1d25',
      'editorWidget.border': '#33333f',
      'editorSuggestWidget.background': '#1d1d25',
      'editorSuggestWidget.foreground': '#e6e6ee',
      'editorSuggestWidget.selectedBackground': '#34417a',
      'minimap.background': '#16161c',
      'scrollbarSlider.background': '#ffffff33',
      'scrollbarSlider.hoverBackground': '#ffffff57',
      'editorError.foreground': '#ffb4ab',
      'editorWarning.foreground': '#ffcf6b',
    },
    rules: [
      {
        token: 'keyword.md',
        foreground: '#8fb4ff',
      },
      {
        token: 'keyword.md.*',
        foreground: '#8fb4ff',
      },
      {
        token: 'meta.separator.md',
        foreground: '#8a93b8',
      },
      {
        token: 'keyword.table.md.*',
        foreground: '#8a93b8',
      },
      {
        token: 'strong.md',
        foreground: '#ffd479',
      },
      {
        token: 'strong.md.*',
        foreground: '#ffd479',
      },
      {
        token: 'emphasis.md',
        foreground: '#c58bff',
      },
      {
        token: 'emphasis.md.*',
        foreground: '#c58bff',
      },
      {
        token: 'comment.md',
        foreground: '#7fe3b5',
      },
      {
        token: 'comment.md.*',
        foreground: '#7fe3b5',
      },
      {
        token: 'string.link.md',
        foreground: '#ff9d7a',
      },
      {
        token: 'string.target.md',
        foreground: '#ff9d7a',
      },
      {
        token: 'string.md',
        foreground: '#8a93b8',
      },
      {
        token: 'variable.source.md',
        foreground: '#dfe6ff',
      },
      {
        token: 'keyword.go',
        foreground: '#c58bff',
      },
      {
        token: 'keyword.go.*',
        foreground: '#c58bff',
      },
      {
        token: 'string.go',
        foreground: '#7fe3b5',
      },
      {
        token: 'comment.go',
        foreground: '#8a93b8',
      },
      {
        token: 'comment.go.*',
        foreground: '#8a93b8',
      },
      {
        token: 'number.go',
        foreground: '#ffd479',
      },
      {
        token: 'number.go.*',
        foreground: '#ffd479',
      },
      {
        token: 'delimiter.go',
        foreground: '#9aa1ab',
      },
      {
        token: 'delimiter.go.*',
        foreground: '#9aa1ab',
      },
      {
        token: 'annotation.go',
        foreground: '#ff9d7a',
      },
      {
        token: 'identifier.go',
        foreground: '#8fb4ff',
      },
      {
        token: 'keyword.type.go',
        foreground: '#5eead4',
      },
      {
        token: 'keyword.const.go',
        foreground: '#5eead4',
      },
    ],
  },
  'gme-minimal-light': {
    base: 'vs',
    inherit: true,
    colors: {
      'editor.background': '#fbfbfa',
      'editor.foreground': '#1f2328',
      'editorLineNumber.foreground': '#c9ccd3',
      'editorLineNumber.activeForeground': '#1f2328',
      'editorCursor.foreground': '#10b981',
      'editor.selectionBackground': '#3056d333',
      'editor.selectionHighlightBackground': '#3056d333',
      'editor.lineHighlightBackground': '#f4f4f3',
      'editorGutter.background': '#fbfbfa',
      'editorWidget.background': '#fbfbfa',
      'editorWidget.border': '#e4e4e7',
      'editorSuggestWidget.background': '#fbfbfa',
      'editorSuggestWidget.foreground': '#1f2328',
      'editorSuggestWidget.selectedBackground': '#ecfdf5',
      'minimap.background': '#fbfbfa',
      'scrollbarSlider.background': '#0000002e',
      'scrollbarSlider.hoverBackground': '#0000004d',
      'editorError.foreground': '#b91c1c',
      'editorWarning.foreground': '#b45309',
    },
    rules: [
      {
        token: 'keyword.md',
        foreground: '#3056d3',
      },
      {
        token: 'keyword.md.*',
        foreground: '#3056d3',
      },
      {
        token: 'meta.separator.md',
        foreground: '#9aa1ab',
      },
      {
        token: 'keyword.table.md.*',
        foreground: '#9aa1ab',
      },
      {
        token: 'strong.md',
        foreground: '#b45309',
      },
      {
        token: 'strong.md.*',
        foreground: '#b45309',
      },
      {
        token: 'emphasis.md',
        foreground: '#7c3aed',
      },
      {
        token: 'emphasis.md.*',
        foreground: '#7c3aed',
      },
      {
        token: 'comment.md',
        foreground: '#0369a1',
      },
      {
        token: 'comment.md.*',
        foreground: '#0369a1',
      },
      {
        token: 'string.link.md',
        foreground: '#be123c',
      },
      {
        token: 'string.target.md',
        foreground: '#be123c',
      },
      {
        token: 'string.md',
        foreground: '#9aa1ab',
      },
      {
        token: 'variable.source.md',
        foreground: '#30343b',
      },
      {
        token: 'keyword.go',
        foreground: '#7c3aed',
      },
      {
        token: 'keyword.go.*',
        foreground: '#7c3aed',
      },
      {
        token: 'string.go',
        foreground: '#0369a1',
      },
      {
        token: 'comment.go',
        foreground: '#9aa1ab',
      },
      {
        token: 'comment.go.*',
        foreground: '#9aa1ab',
      },
      {
        token: 'number.go',
        foreground: '#b45309',
      },
      {
        token: 'number.go.*',
        foreground: '#b45309',
      },
      {
        token: 'delimiter.go',
        foreground: '#5c5c69',
      },
      {
        token: 'delimiter.go.*',
        foreground: '#5c5c69',
      },
      {
        token: 'annotation.go',
        foreground: '#be123c',
      },
      {
        token: 'identifier.go',
        foreground: '#3056d3',
      },
      {
        token: 'keyword.type.go',
        foreground: '#0f766e',
      },
      {
        token: 'keyword.const.go',
        foreground: '#0f766e',
      },
    ],
  },
  'gme-minimal-dark': {
    base: 'vs-dark',
    inherit: true,
    colors: {
      'editor.background': '#141416',
      'editor.foreground': '#e7e7ea',
      'editorLineNumber.foreground': '#ffffff38',
      'editorLineNumber.activeForeground': '#e7e7ea',
      'editorCursor.foreground': '#34d399',
      'editor.selectionBackground': '#8fb4ff42',
      'editor.selectionHighlightBackground': '#8fb4ff42',
      'editor.lineHighlightBackground': '#1e1e21',
      'editorGutter.background': '#141416',
      'editorWidget.background': '#141416',
      'editorWidget.border': '#28282c',
      'editorSuggestWidget.background': '#141416',
      'editorSuggestWidget.foreground': '#e7e7ea',
      'editorSuggestWidget.selectedBackground': '#34d39924',
      'minimap.background': '#141416',
      'scrollbarSlider.background': '#ffffff33',
      'scrollbarSlider.hoverBackground': '#ffffff57',
      'editorError.foreground': '#f87171',
      'editorWarning.foreground': '#fbbf24',
    },
    rules: [
      {
        token: 'keyword.md',
        foreground: '#8fb4ff',
      },
      {
        token: 'keyword.md.*',
        foreground: '#8fb4ff',
      },
      {
        token: 'meta.separator.md',
        foreground: '#8a93b8',
      },
      {
        token: 'keyword.table.md.*',
        foreground: '#8a93b8',
      },
      {
        token: 'strong.md',
        foreground: '#ffd479',
      },
      {
        token: 'strong.md.*',
        foreground: '#ffd479',
      },
      {
        token: 'emphasis.md',
        foreground: '#c58bff',
      },
      {
        token: 'emphasis.md.*',
        foreground: '#c58bff',
      },
      {
        token: 'comment.md',
        foreground: '#7fe3b5',
      },
      {
        token: 'comment.md.*',
        foreground: '#7fe3b5',
      },
      {
        token: 'string.link.md',
        foreground: '#ff9d7a',
      },
      {
        token: 'string.target.md',
        foreground: '#ff9d7a',
      },
      {
        token: 'string.md',
        foreground: '#8a93b8',
      },
      {
        token: 'variable.source.md',
        foreground: '#dfe6ff',
      },
      {
        token: 'keyword.go',
        foreground: '#c58bff',
      },
      {
        token: 'keyword.go.*',
        foreground: '#c58bff',
      },
      {
        token: 'string.go',
        foreground: '#7fe3b5',
      },
      {
        token: 'comment.go',
        foreground: '#8a93b8',
      },
      {
        token: 'comment.go.*',
        foreground: '#8a93b8',
      },
      {
        token: 'number.go',
        foreground: '#ffd479',
      },
      {
        token: 'number.go.*',
        foreground: '#ffd479',
      },
      {
        token: 'delimiter.go',
        foreground: '#9aa1ab',
      },
      {
        token: 'delimiter.go.*',
        foreground: '#9aa1ab',
      },
      {
        token: 'annotation.go',
        foreground: '#ff9d7a',
      },
      {
        token: 'identifier.go',
        foreground: '#8fb4ff',
      },
      {
        token: 'keyword.type.go',
        foreground: '#5eead4',
      },
      {
        token: 'keyword.const.go',
        foreground: '#5eead4',
      },
    ],
  },
} as const;
export type GeneratedEditorThemeName = keyof typeof generatedEditorThemes;
