// Generated by scripts/generate-editor-themes.mjs. Do not edit.
export const generatedEditorThemes = {
    'gme-glass-light': {
        base: 'vs',
        inherit: true,
        colors: {
            focusBorder: '#5b7cff',
            'editor.background': '#00000000',
            'editor.foreground': '#1c2338',
            'editorLineNumber.foreground': '#c9ccd3',
            'editorLineNumber.activeForeground': '#1c2338',
            'editorCursor.foreground': '#5b7cff',
            'editor.selectionBackground': '#3056d333',
            'editor.selectionHighlightBackground': '#3056d333',
            'editor.lineHighlightBackground': '#46548c1f',
            'editorGutter.background': '#00000000',
            'editorWidget.background': '#ffffff57',
            'editorHoverWidget.background': '#ffffffcc',
            'editorWidget.border': '#46548c3d',
            'editorSuggestWidget.background': '#ffffff57',
            'editorSuggestWidget.foreground': '#1c2338',
            'editorSuggestWidget.selectedBackground': '#5b7cff24',
            'minimap.background': '#00000000',
            'scrollbarSlider.background': '#0000002e',
            'scrollbarSlider.hoverBackground': '#0000004d',
            'editorError.foreground': '#c0324b',
            'editorWarning.foreground': '#b7791f',
            'diffEditor.insertedTextBackground': '#5b7cff24',
            'diffEditor.insertedLineBackground': '#5b7cff24',
            'diffEditor.removedTextBackground': '#b3261e2e',
            'diffEditor.removedLineBackground': '#b3261e2e',
        },
        rules: [
            {
                token: 'keyword',
                foreground: '#7c3aed',
            },
            {
                token: 'string',
                foreground: '#0369a1',
            },
            {
                token: 'comment',
                foreground: '#9aa1ab',
            },
            {
                token: 'number',
                foreground: '#b45309',
            },
            {
                token: 'type',
                foreground: '#0f766e',
            },
            {
                token: 'delimiter',
                foreground: '#5c5c69',
            },
            {
                token: 'operator',
                foreground: '#5c5c69',
            },
            {
                token: 'annotation',
                foreground: '#be123c',
            },
            {
                token: 'attribute.name',
                foreground: '#be123c',
            },
            {
                token: 'tag',
                foreground: '#be123c',
            },
            {
                token: 'predefined',
                foreground: '#3056d3',
            },
            {
                token: 'number.hex',
                foreground: '#b45309',
            },
            {
                token: 'delimiter.html',
                foreground: '#5c5c69',
            },
            {
                token: 'delimiter.xml',
                foreground: '#5c5c69',
            },
            {
                token: 'string.key.json',
                foreground: '#be123c',
            },
            {
                token: 'string.value.json',
                foreground: '#0369a1',
            },
            {
                token: 'attribute.value',
                foreground: '#0369a1',
            },
            {
                token: 'attribute.value.number',
                foreground: '#b45309',
            },
            {
                token: 'attribute.value.unit',
                foreground: '#b45309',
            },
            {
                token: 'attribute.value.number.css',
                foreground: '#b45309',
            },
            {
                token: 'attribute.value.unit.css',
                foreground: '#b45309',
            },
            {
                token: 'attribute.value.hex.css',
                foreground: '#b45309',
            },
            {
                token: 'attribute.value.html',
                foreground: '#0369a1',
            },
            {
                token: 'attribute.value.xml',
                foreground: '#0369a1',
            },
            {
                token: 'string.html',
                foreground: '#0369a1',
            },
            {
                token: 'string.sql',
                foreground: '#0369a1',
            },
            {
                token: 'string.yaml',
                foreground: '#0369a1',
            },
            {
                token: 'keyword.json',
                foreground: '#7c3aed',
            },
            {
                token: 'keyword.flow',
                foreground: '#7c3aed',
            },
            {
                token: 'keyword.flow.scss',
                foreground: '#7c3aed',
            },
            {
                token: 'operator.scss',
                foreground: '#5c5c69',
            },
            {
                token: 'operator.sql',
                foreground: '#5c5c69',
            },
            {
                token: 'operator.swift',
                foreground: '#5c5c69',
            },
            {
                token: 'predefined.sql',
                foreground: '#3056d3',
            },
            {
                token: 'keyword.md',
                foreground: '#3056d3',
            },
            {
                token: 'keyword.md.*',
                foreground: '#3056d3',
            },
            {
                token: 'meta.separator.md',
                foreground: '#9aa1ab',
            },
            {
                token: 'keyword.table.md.*',
                foreground: '#9aa1ab',
            },
            {
                token: 'strong.md',
                foreground: '#b45309',
            },
            {
                token: 'strong.md.*',
                foreground: '#b45309',
            },
            {
                token: 'emphasis.md',
                foreground: '#7c3aed',
            },
            {
                token: 'emphasis.md.*',
                foreground: '#7c3aed',
            },
            {
                token: 'comment.md',
                foreground: '#0369a1',
            },
            {
                token: 'comment.md.*',
                foreground: '#0369a1',
            },
            {
                token: 'string.link.md',
                foreground: '#be123c',
            },
            {
                token: 'string.target.md',
                foreground: '#be123c',
            },
            {
                token: 'string.md',
                foreground: '#9aa1ab',
            },
            {
                token: 'variable.source.md',
                foreground: '#30343b',
            },
            {
                token: 'keyword.go',
                foreground: '#7c3aed',
            },
            {
                token: 'keyword.go.*',
                foreground: '#7c3aed',
            },
            {
                token: 'string.go',
                foreground: '#0369a1',
            },
            {
                token: 'comment.go',
                foreground: '#9aa1ab',
            },
            {
                token: 'comment.go.*',
                foreground: '#9aa1ab',
            },
            {
                token: 'number.go',
                foreground: '#b45309',
            },
            {
                token: 'number.go.*',
                foreground: '#b45309',
            },
            {
                token: 'delimiter.go',
                foreground: '#5c5c69',
            },
            {
                token: 'delimiter.go.*',
                foreground: '#5c5c69',
            },
            {
                token: 'annotation.go',
                foreground: '#be123c',
            },
            {
                token: 'identifier.go',
                foreground: '#3056d3',
            },
            {
                token: 'keyword.type.go',
                foreground: '#0f766e',
            },
            {
                token: 'keyword.const.go',
                foreground: '#0f766e',
            },
        ],
    },
    'gme-glass-dark': {
        base: 'vs-dark',
        inherit: true,
        colors: {
            focusBorder: '#7aa2ff',
            'editor.background': '#00000000',
            'editor.foreground': '#eaf0ff',
            'editorLineNumber.foreground': '#ffffff38',
            'editorLineNumber.activeForeground': '#eaf0ff',
            'editorCursor.foreground': '#7aa2ff',
            'editor.selectionBackground': '#8fb4ff42',
            'editor.selectionHighlightBackground': '#8fb4ff42',
            'editor.lineHighlightBackground': '#ffffff29',
            'editorGutter.background': '#00000000',
            'editorWidget.background': '#ffffff1a',
            'editorHoverWidget.background': '#1c1e36d1',
            'editorWidget.border': '#ffffff2e',
            'editorSuggestWidget.background': '#ffffff1a',
            'editorSuggestWidget.foreground': '#eaf0ff',
            'editorSuggestWidget.selectedBackground': '#7aa2ff29',
            'minimap.background': '#00000000',
            'scrollbarSlider.background': '#ffffff33',
            'scrollbarSlider.hoverBackground': '#ffffff57',
            'editorError.foreground': '#ff7a90',
            'editorWarning.foreground': '#ffcf6b',
            'diffEditor.insertedTextBackground': '#7aa2ff29',
            'diffEditor.insertedLineBackground': '#7aa2ff29',
            'diffEditor.removedTextBackground': '#ffb4ab2e',
            'diffEditor.removedLineBackground': '#ffb4ab2e',
        },
        rules: [
            {
                token: 'keyword',
                foreground: '#c58bff',
            },
            {
                token: 'string',
                foreground: '#7fe3b5',
            },
            {
                token: 'comment',
                foreground: '#8a93b8',
            },
            {
                token: 'number',
                foreground: '#ffd479',
            },
            {
                token: 'type',
                foreground: '#5eead4',
            },
            {
                token: 'delimiter',
                foreground: '#9aa1ab',
            },
            {
                token: 'operator',
                foreground: '#9aa1ab',
            },
            {
                token: 'annotation',
                foreground: '#ff9d7a',
            },
            {
                token: 'attribute.name',
                foreground: '#ff9d7a',
            },
            {
                token: 'tag',
                foreground: '#ff9d7a',
            },
            {
                token: 'predefined',
                foreground: '#8fb4ff',
            },
            {
                token: 'number.hex',
                foreground: '#ffd479',
            },
            {
                token: 'delimiter.html',
                foreground: '#9aa1ab',
            },
            {
                token: 'delimiter.xml',
                foreground: '#9aa1ab',
            },
            {
                token: 'string.key.json',
                foreground: '#ff9d7a',
            },
            {
                token: 'string.value.json',
                foreground: '#7fe3b5',
            },
            {
                token: 'attribute.value',
                foreground: '#7fe3b5',
            },
            {
                token: 'attribute.value.number',
                foreground: '#ffd479',
            },
            {
                token: 'attribute.value.unit',
                foreground: '#ffd479',
            },
            {
                token: 'attribute.value.number.css',
                foreground: '#ffd479',
            },
            {
                token: 'attribute.value.unit.css',
                foreground: '#ffd479',
            },
            {
                token: 'attribute.value.hex.css',
                foreground: '#ffd479',
            },
            {
                token: 'attribute.value.html',
                foreground: '#7fe3b5',
            },
            {
                token: 'attribute.value.xml',
                foreground: '#7fe3b5',
            },
            {
                token: 'string.html',
                foreground: '#7fe3b5',
            },
            {
                token: 'string.sql',
                foreground: '#7fe3b5',
            },
            {
                token: 'string.yaml',
                foreground: '#7fe3b5',
            },
            {
                token: 'keyword.json',
                foreground: '#c58bff',
            },
            {
                token: 'keyword.flow',
                foreground: '#c58bff',
            },
            {
                token: 'keyword.flow.scss',
                foreground: '#c58bff',
            },
            {
                token: 'operator.scss',
                foreground: '#9aa1ab',
            },
            {
                token: 'operator.sql',
                foreground: '#9aa1ab',
            },
            {
                token: 'operator.swift',
                foreground: '#9aa1ab',
            },
            {
                token: 'predefined.sql',
                foreground: '#8fb4ff',
            },
            {
                token: 'keyword.md',
                foreground: '#8fb4ff',
            },
            {
                token: 'keyword.md.*',
                foreground: '#8fb4ff',
            },
            {
                token: 'meta.separator.md',
                foreground: '#8a93b8',
            },
            {
                token: 'keyword.table.md.*',
                foreground: '#8a93b8',
            },
            {
                token: 'strong.md',
                foreground: '#ffd479',
            },
            {
                token: 'strong.md.*',
                foreground: '#ffd479',
            },
            {
                token: 'emphasis.md',
                foreground: '#c58bff',
            },
            {
                token: 'emphasis.md.*',
                foreground: '#c58bff',
            },
            {
                token: 'comment.md',
                foreground: '#7fe3b5',
            },
            {
                token: 'comment.md.*',
                foreground: '#7fe3b5',
            },
            {
                token: 'string.link.md',
                foreground: '#ff9d7a',
            },
            {
                token: 'string.target.md',
                foreground: '#ff9d7a',
            },
            {
                token: 'string.md',
                foreground: '#8a93b8',
            },
            {
                token: 'variable.source.md',
                foreground: '#dfe6ff',
            },
            {
                token: 'keyword.go',
                foreground: '#c58bff',
            },
            {
                token: 'keyword.go.*',
                foreground: '#c58bff',
            },
            {
                token: 'string.go',
                foreground: '#7fe3b5',
            },
            {
                token: 'comment.go',
                foreground: '#8a93b8',
            },
            {
                token: 'comment.go.*',
                foreground: '#8a93b8',
            },
            {
                token: 'number.go',
                foreground: '#ffd479',
            },
            {
                token: 'number.go.*',
                foreground: '#ffd479',
            },
            {
                token: 'delimiter.go',
                foreground: '#9aa1ab',
            },
            {
                token: 'delimiter.go.*',
                foreground: '#9aa1ab',
            },
            {
                token: 'annotation.go',
                foreground: '#ff9d7a',
            },
            {
                token: 'identifier.go',
                foreground: '#8fb4ff',
            },
            {
                token: 'keyword.type.go',
                foreground: '#5eead4',
            },
            {
                token: 'keyword.const.go',
                foreground: '#5eead4',
            },
        ],
    },
    'gme-material-light': {
        base: 'vs',
        inherit: true,
        colors: {
            focusBorder: '#4f6bed',
            'editor.background': '#00000000',
            'editor.foreground': '#1b1b22',
            'editorLineNumber.foreground': '#c9ccd3',
            'editorLineNumber.activeForeground': '#1b1b22',
            'editorCursor.foreground': '#4f6bed',
            'editor.selectionBackground': '#3056d333',
            'editor.selectionHighlightBackground': '#3056d333',
            'editor.lineHighlightBackground': '#eceaf6',
            'editorGutter.background': '#00000000',
            'editorWidget.background': '#ffffff',
            'editorHoverWidget.background': '#f3f1fb',
            'editorWidget.border': '#e3e1ee',
            'editorSuggestWidget.background': '#ffffff',
            'editorSuggestWidget.foreground': '#1b1b22',
            'editorSuggestWidget.selectedBackground': '#dfe4ff',
            'minimap.background': '#00000000',
            'scrollbarSlider.background': '#0000002e',
            'scrollbarSlider.hoverBackground': '#0000004d',
            'editorError.foreground': '#b3261e',
            'editorWarning.foreground': '#8a5a00',
            'diffEditor.insertedTextBackground': '#dfe4ff',
            'diffEditor.insertedLineBackground': '#dfe4ff',
            'diffEditor.removedTextBackground': '#b3261e2e',
            'diffEditor.removedLineBackground': '#b3261e2e',
        },
        rules: [
            {
                token: 'keyword',
                foreground: '#7c3aed',
            },
            {
                token: 'string',
                foreground: '#0369a1',
            },
            {
                token: 'comment',
                foreground: '#9aa1ab',
            },
            {
                token: 'number',
                foreground: '#b45309',
            },
            {
                token: 'type',
                foreground: '#0f766e',
            },
            {
                token: 'delimiter',
                foreground: '#5c5c69',
            },
            {
                token: 'operator',
                foreground: '#5c5c69',
            },
            {
                token: 'annotation',
                foreground: '#be123c',
            },
            {
                token: 'attribute.name',
                foreground: '#be123c',
            },
            {
                token: 'tag',
                foreground: '#be123c',
            },
            {
                token: 'predefined',
                foreground: '#3056d3',
            },
            {
                token: 'number.hex',
                foreground: '#b45309',
            },
            {
                token: 'delimiter.html',
                foreground: '#5c5c69',
            },
            {
                token: 'delimiter.xml',
                foreground: '#5c5c69',
            },
            {
                token: 'string.key.json',
                foreground: '#be123c',
            },
            {
                token: 'string.value.json',
                foreground: '#0369a1',
            },
            {
                token: 'attribute.value',
                foreground: '#0369a1',
            },
            {
                token: 'attribute.value.number',
                foreground: '#b45309',
            },
            {
                token: 'attribute.value.unit',
                foreground: '#b45309',
            },
            {
                token: 'attribute.value.number.css',
                foreground: '#b45309',
            },
            {
                token: 'attribute.value.unit.css',
                foreground: '#b45309',
            },
            {
                token: 'attribute.value.hex.css',
                foreground: '#b45309',
            },
            {
                token: 'attribute.value.html',
                foreground: '#0369a1',
            },
            {
                token: 'attribute.value.xml',
                foreground: '#0369a1',
            },
            {
                token: 'string.html',
                foreground: '#0369a1',
            },
            {
                token: 'string.sql',
                foreground: '#0369a1',
            },
            {
                token: 'string.yaml',
                foreground: '#0369a1',
            },
            {
                token: 'keyword.json',
                foreground: '#7c3aed',
            },
            {
                token: 'keyword.flow',
                foreground: '#7c3aed',
            },
            {
                token: 'keyword.flow.scss',
                foreground: '#7c3aed',
            },
            {
                token: 'operator.scss',
                foreground: '#5c5c69',
            },
            {
                token: 'operator.sql',
                foreground: '#5c5c69',
            },
            {
                token: 'operator.swift',
                foreground: '#5c5c69',
            },
            {
                token: 'predefined.sql',
                foreground: '#3056d3',
            },
            {
                token: 'keyword.md',
                foreground: '#3056d3',
            },
            {
                token: 'keyword.md.*',
                foreground: '#3056d3',
            },
            {
                token: 'meta.separator.md',
                foreground: '#9aa1ab',
            },
            {
                token: 'keyword.table.md.*',
                foreground: '#9aa1ab',
            },
            {
                token: 'strong.md',
                foreground: '#b45309',
            },
            {
                token: 'strong.md.*',
                foreground: '#b45309',
            },
            {
                token: 'emphasis.md',
                foreground: '#7c3aed',
            },
            {
                token: 'emphasis.md.*',
                foreground: '#7c3aed',
            },
            {
                token: 'comment.md',
                foreground: '#0369a1',
            },
            {
                token: 'comment.md.*',
                foreground: '#0369a1',
            },
            {
                token: 'string.link.md',
                foreground: '#be123c',
            },
            {
                token: 'string.target.md',
                foreground: '#be123c',
            },
            {
                token: 'string.md',
                foreground: '#9aa1ab',
            },
            {
                token: 'variable.source.md',
                foreground: '#30343b',
            },
            {
                token: 'keyword.go',
                foreground: '#7c3aed',
            },
            {
                token: 'keyword.go.*',
                foreground: '#7c3aed',
            },
            {
                token: 'string.go',
                foreground: '#0369a1',
            },
            {
                token: 'comment.go',
                foreground: '#9aa1ab',
            },
            {
                token: 'comment.go.*',
                foreground: '#9aa1ab',
            },
            {
                token: 'number.go',
                foreground: '#b45309',
            },
            {
                token: 'number.go.*',
                foreground: '#b45309',
            },
            {
                token: 'delimiter.go',
                foreground: '#5c5c69',
            },
            {
                token: 'delimiter.go.*',
                foreground: '#5c5c69',
            },
            {
                token: 'annotation.go',
                foreground: '#be123c',
            },
            {
                token: 'identifier.go',
                foreground: '#3056d3',
            },
            {
                token: 'keyword.type.go',
                foreground: '#0f766e',
            },
            {
                token: 'keyword.const.go',
                foreground: '#0f766e',
            },
        ],
    },
    'gme-material-dark': {
        base: 'vs-dark',
        inherit: true,
        colors: {
            focusBorder: '#b3c2ff',
            'editor.background': '#00000000',
            'editor.foreground': '#e6e6ee',
            'editorLineNumber.foreground': '#ffffff38',
            'editorLineNumber.activeForeground': '#e6e6ee',
            'editorCursor.foreground': '#b3c2ff',
            'editor.selectionBackground': '#8fb4ff42',
            'editor.selectionHighlightBackground': '#8fb4ff42',
            'editor.lineHighlightBackground': '#2a2a34',
            'editorGutter.background': '#00000000',
            'editorWidget.background': '#1d1d25',
            'editorHoverWidget.background': '#24242e',
            'editorWidget.border': '#33333f',
            'editorSuggestWidget.background': '#1d1d25',
            'editorSuggestWidget.foreground': '#e6e6ee',
            'editorSuggestWidget.selectedBackground': '#34417a',
            'minimap.background': '#00000000',
            'scrollbarSlider.background': '#ffffff33',
            'scrollbarSlider.hoverBackground': '#ffffff57',
            'editorError.foreground': '#ffb4ab',
            'editorWarning.foreground': '#ffcf6b',
            'diffEditor.insertedTextBackground': '#34417a',
            'diffEditor.insertedLineBackground': '#34417a',
            'diffEditor.removedTextBackground': '#ffb4ab2e',
            'diffEditor.removedLineBackground': '#ffb4ab2e',
        },
        rules: [
            {
                token: 'keyword',
                foreground: '#c58bff',
            },
            {
                token: 'string',
                foreground: '#7fe3b5',
            },
            {
                token: 'comment',
                foreground: '#8a93b8',
            },
            {
                token: 'number',
                foreground: '#ffd479',
            },
            {
                token: 'type',
                foreground: '#5eead4',
            },
            {
                token: 'delimiter',
                foreground: '#9aa1ab',
            },
            {
                token: 'operator',
                foreground: '#9aa1ab',
            },
            {
                token: 'annotation',
                foreground: '#ff9d7a',
            },
            {
                token: 'attribute.name',
                foreground: '#ff9d7a',
            },
            {
                token: 'tag',
                foreground: '#ff9d7a',
            },
            {
                token: 'predefined',
                foreground: '#8fb4ff',
            },
            {
                token: 'number.hex',
                foreground: '#ffd479',
            },
            {
                token: 'delimiter.html',
                foreground: '#9aa1ab',
            },
            {
                token: 'delimiter.xml',
                foreground: '#9aa1ab',
            },
            {
                token: 'string.key.json',
                foreground: '#ff9d7a',
            },
            {
                token: 'string.value.json',
                foreground: '#7fe3b5',
            },
            {
                token: 'attribute.value',
                foreground: '#7fe3b5',
            },
            {
                token: 'attribute.value.number',
                foreground: '#ffd479',
            },
            {
                token: 'attribute.value.unit',
                foreground: '#ffd479',
            },
            {
                token: 'attribute.value.number.css',
                foreground: '#ffd479',
            },
            {
                token: 'attribute.value.unit.css',
                foreground: '#ffd479',
            },
            {
                token: 'attribute.value.hex.css',
                foreground: '#ffd479',
            },
            {
                token: 'attribute.value.html',
                foreground: '#7fe3b5',
            },
            {
                token: 'attribute.value.xml',
                foreground: '#7fe3b5',
            },
            {
                token: 'string.html',
                foreground: '#7fe3b5',
            },
            {
                token: 'string.sql',
                foreground: '#7fe3b5',
            },
            {
                token: 'string.yaml',
                foreground: '#7fe3b5',
            },
            {
                token: 'keyword.json',
                foreground: '#c58bff',
            },
            {
                token: 'keyword.flow',
                foreground: '#c58bff',
            },
            {
                token: 'keyword.flow.scss',
                foreground: '#c58bff',
            },
            {
                token: 'operator.scss',
                foreground: '#9aa1ab',
            },
            {
                token: 'operator.sql',
                foreground: '#9aa1ab',
            },
            {
                token: 'operator.swift',
                foreground: '#9aa1ab',
            },
            {
                token: 'predefined.sql',
                foreground: '#8fb4ff',
            },
            {
                token: 'keyword.md',
                foreground: '#8fb4ff',
            },
            {
                token: 'keyword.md.*',
                foreground: '#8fb4ff',
            },
            {
                token: 'meta.separator.md',
                foreground: '#8a93b8',
            },
            {
                token: 'keyword.table.md.*',
                foreground: '#8a93b8',
            },
            {
                token: 'strong.md',
                foreground: '#ffd479',
            },
            {
                token: 'strong.md.*',
                foreground: '#ffd479',
            },
            {
                token: 'emphasis.md',
                foreground: '#c58bff',
            },
            {
                token: 'emphasis.md.*',
                foreground: '#c58bff',
            },
            {
                token: 'comment.md',
                foreground: '#7fe3b5',
            },
            {
                token: 'comment.md.*',
                foreground: '#7fe3b5',
            },
            {
                token: 'string.link.md',
                foreground: '#ff9d7a',
            },
            {
                token: 'string.target.md',
                foreground: '#ff9d7a',
            },
            {
                token: 'string.md',
                foreground: '#8a93b8',
            },
            {
                token: 'variable.source.md',
                foreground: '#dfe6ff',
            },
            {
                token: 'keyword.go',
                foreground: '#c58bff',
            },
            {
                token: 'keyword.go.*',
                foreground: '#c58bff',
            },
            {
                token: 'string.go',
                foreground: '#7fe3b5',
            },
            {
                token: 'comment.go',
                foreground: '#8a93b8',
            },
            {
                token: 'comment.go.*',
                foreground: '#8a93b8',
            },
            {
                token: 'number.go',
                foreground: '#ffd479',
            },
            {
                token: 'number.go.*',
                foreground: '#ffd479',
            },
            {
                token: 'delimiter.go',
                foreground: '#9aa1ab',
            },
            {
                token: 'delimiter.go.*',
                foreground: '#9aa1ab',
            },
            {
                token: 'annotation.go',
                foreground: '#ff9d7a',
            },
            {
                token: 'identifier.go',
                foreground: '#8fb4ff',
            },
            {
                token: 'keyword.type.go',
                foreground: '#5eead4',
            },
            {
                token: 'keyword.const.go',
                foreground: '#5eead4',
            },
        ],
    },
    'gme-minimal-light': {
        base: 'vs',
        inherit: true,
        colors: {
            focusBorder: '#10b981',
            'editor.background': '#00000000',
            'editor.foreground': '#1f2328',
            'editorLineNumber.foreground': '#c9ccd3',
            'editorLineNumber.activeForeground': '#1f2328',
            'editorCursor.foreground': '#10b981',
            'editor.selectionBackground': '#3056d333',
            'editor.selectionHighlightBackground': '#3056d333',
            'editor.lineHighlightBackground': '#f4f4f3',
            'editorGutter.background': '#00000000',
            'editorWidget.background': '#fbfbfa',
            'editorHoverWidget.background': '#ffffff',
            'editorWidget.border': '#e4e4e7',
            'editorSuggestWidget.background': '#fbfbfa',
            'editorSuggestWidget.foreground': '#1f2328',
            'editorSuggestWidget.selectedBackground': '#ecfdf5',
            'minimap.background': '#00000000',
            'scrollbarSlider.background': '#0000002e',
            'scrollbarSlider.hoverBackground': '#0000004d',
            'editorError.foreground': '#b91c1c',
            'editorWarning.foreground': '#b45309',
            'diffEditor.insertedTextBackground': '#ecfdf5',
            'diffEditor.insertedLineBackground': '#ecfdf5',
            'diffEditor.removedTextBackground': '#b3261e2e',
            'diffEditor.removedLineBackground': '#b3261e2e',
        },
        rules: [
            {
                token: 'keyword',
                foreground: '#7c3aed',
            },
            {
                token: 'string',
                foreground: '#0369a1',
            },
            {
                token: 'comment',
                foreground: '#9aa1ab',
            },
            {
                token: 'number',
                foreground: '#b45309',
            },
            {
                token: 'type',
                foreground: '#0f766e',
            },
            {
                token: 'delimiter',
                foreground: '#5c5c69',
            },
            {
                token: 'operator',
                foreground: '#5c5c69',
            },
            {
                token: 'annotation',
                foreground: '#be123c',
            },
            {
                token: 'attribute.name',
                foreground: '#be123c',
            },
            {
                token: 'tag',
                foreground: '#be123c',
            },
            {
                token: 'predefined',
                foreground: '#3056d3',
            },
            {
                token: 'number.hex',
                foreground: '#b45309',
            },
            {
                token: 'delimiter.html',
                foreground: '#5c5c69',
            },
            {
                token: 'delimiter.xml',
                foreground: '#5c5c69',
            },
            {
                token: 'string.key.json',
                foreground: '#be123c',
            },
            {
                token: 'string.value.json',
                foreground: '#0369a1',
            },
            {
                token: 'attribute.value',
                foreground: '#0369a1',
            },
            {
                token: 'attribute.value.number',
                foreground: '#b45309',
            },
            {
                token: 'attribute.value.unit',
                foreground: '#b45309',
            },
            {
                token: 'attribute.value.number.css',
                foreground: '#b45309',
            },
            {
                token: 'attribute.value.unit.css',
                foreground: '#b45309',
            },
            {
                token: 'attribute.value.hex.css',
                foreground: '#b45309',
            },
            {
                token: 'attribute.value.html',
                foreground: '#0369a1',
            },
            {
                token: 'attribute.value.xml',
                foreground: '#0369a1',
            },
            {
                token: 'string.html',
                foreground: '#0369a1',
            },
            {
                token: 'string.sql',
                foreground: '#0369a1',
            },
            {
                token: 'string.yaml',
                foreground: '#0369a1',
            },
            {
                token: 'keyword.json',
                foreground: '#7c3aed',
            },
            {
                token: 'keyword.flow',
                foreground: '#7c3aed',
            },
            {
                token: 'keyword.flow.scss',
                foreground: '#7c3aed',
            },
            {
                token: 'operator.scss',
                foreground: '#5c5c69',
            },
            {
                token: 'operator.sql',
                foreground: '#5c5c69',
            },
            {
                token: 'operator.swift',
                foreground: '#5c5c69',
            },
            {
                token: 'predefined.sql',
                foreground: '#3056d3',
            },
            {
                token: 'keyword.md',
                foreground: '#3056d3',
            },
            {
                token: 'keyword.md.*',
                foreground: '#3056d3',
            },
            {
                token: 'meta.separator.md',
                foreground: '#9aa1ab',
            },
            {
                token: 'keyword.table.md.*',
                foreground: '#9aa1ab',
            },
            {
                token: 'strong.md',
                foreground: '#b45309',
            },
            {
                token: 'strong.md.*',
                foreground: '#b45309',
            },
            {
                token: 'emphasis.md',
                foreground: '#7c3aed',
            },
            {
                token: 'emphasis.md.*',
                foreground: '#7c3aed',
            },
            {
                token: 'comment.md',
                foreground: '#0369a1',
            },
            {
                token: 'comment.md.*',
                foreground: '#0369a1',
            },
            {
                token: 'string.link.md',
                foreground: '#be123c',
            },
            {
                token: 'string.target.md',
                foreground: '#be123c',
            },
            {
                token: 'string.md',
                foreground: '#9aa1ab',
            },
            {
                token: 'variable.source.md',
                foreground: '#30343b',
            },
            {
                token: 'keyword.go',
                foreground: '#7c3aed',
            },
            {
                token: 'keyword.go.*',
                foreground: '#7c3aed',
            },
            {
                token: 'string.go',
                foreground: '#0369a1',
            },
            {
                token: 'comment.go',
                foreground: '#9aa1ab',
            },
            {
                token: 'comment.go.*',
                foreground: '#9aa1ab',
            },
            {
                token: 'number.go',
                foreground: '#b45309',
            },
            {
                token: 'number.go.*',
                foreground: '#b45309',
            },
            {
                token: 'delimiter.go',
                foreground: '#5c5c69',
            },
            {
                token: 'delimiter.go.*',
                foreground: '#5c5c69',
            },
            {
                token: 'annotation.go',
                foreground: '#be123c',
            },
            {
                token: 'identifier.go',
                foreground: '#3056d3',
            },
            {
                token: 'keyword.type.go',
                foreground: '#0f766e',
            },
            {
                token: 'keyword.const.go',
                foreground: '#0f766e',
            },
        ],
    },
    'gme-minimal-dark': {
        base: 'vs-dark',
        inherit: true,
        colors: {
            focusBorder: '#34d399',
            'editor.background': '#00000000',
            'editor.foreground': '#e7e7ea',
            'editorLineNumber.foreground': '#ffffff38',
            'editorLineNumber.activeForeground': '#e7e7ea',
            'editorCursor.foreground': '#34d399',
            'editor.selectionBackground': '#8fb4ff42',
            'editor.selectionHighlightBackground': '#8fb4ff42',
            'editor.lineHighlightBackground': '#1e1e21',
            'editorGutter.background': '#00000000',
            'editorWidget.background': '#141416',
            'editorHoverWidget.background': '#1c1c1f',
            'editorWidget.border': '#28282c',
            'editorSuggestWidget.background': '#141416',
            'editorSuggestWidget.foreground': '#e7e7ea',
            'editorSuggestWidget.selectedBackground': '#34d39924',
            'minimap.background': '#00000000',
            'scrollbarSlider.background': '#ffffff33',
            'scrollbarSlider.hoverBackground': '#ffffff57',
            'editorError.foreground': '#f87171',
            'editorWarning.foreground': '#fbbf24',
            'diffEditor.insertedTextBackground': '#34d39924',
            'diffEditor.insertedLineBackground': '#34d39924',
            'diffEditor.removedTextBackground': '#ffb4ab2e',
            'diffEditor.removedLineBackground': '#ffb4ab2e',
        },
        rules: [
            {
                token: 'keyword',
                foreground: '#c58bff',
            },
            {
                token: 'string',
                foreground: '#7fe3b5',
            },
            {
                token: 'comment',
                foreground: '#8a93b8',
            },
            {
                token: 'number',
                foreground: '#ffd479',
            },
            {
                token: 'type',
                foreground: '#5eead4',
            },
            {
                token: 'delimiter',
                foreground: '#9aa1ab',
            },
            {
                token: 'operator',
                foreground: '#9aa1ab',
            },
            {
                token: 'annotation',
                foreground: '#ff9d7a',
            },
            {
                token: 'attribute.name',
                foreground: '#ff9d7a',
            },
            {
                token: 'tag',
                foreground: '#ff9d7a',
            },
            {
                token: 'predefined',
                foreground: '#8fb4ff',
            },
            {
                token: 'number.hex',
                foreground: '#ffd479',
            },
            {
                token: 'delimiter.html',
                foreground: '#9aa1ab',
            },
            {
                token: 'delimiter.xml',
                foreground: '#9aa1ab',
            },
            {
                token: 'string.key.json',
                foreground: '#ff9d7a',
            },
            {
                token: 'string.value.json',
                foreground: '#7fe3b5',
            },
            {
                token: 'attribute.value',
                foreground: '#7fe3b5',
            },
            {
                token: 'attribute.value.number',
                foreground: '#ffd479',
            },
            {
                token: 'attribute.value.unit',
                foreground: '#ffd479',
            },
            {
                token: 'attribute.value.number.css',
                foreground: '#ffd479',
            },
            {
                token: 'attribute.value.unit.css',
                foreground: '#ffd479',
            },
            {
                token: 'attribute.value.hex.css',
                foreground: '#ffd479',
            },
            {
                token: 'attribute.value.html',
                foreground: '#7fe3b5',
            },
            {
                token: 'attribute.value.xml',
                foreground: '#7fe3b5',
            },
            {
                token: 'string.html',
                foreground: '#7fe3b5',
            },
            {
                token: 'string.sql',
                foreground: '#7fe3b5',
            },
            {
                token: 'string.yaml',
                foreground: '#7fe3b5',
            },
            {
                token: 'keyword.json',
                foreground: '#c58bff',
            },
            {
                token: 'keyword.flow',
                foreground: '#c58bff',
            },
            {
                token: 'keyword.flow.scss',
                foreground: '#c58bff',
            },
            {
                token: 'operator.scss',
                foreground: '#9aa1ab',
            },
            {
                token: 'operator.sql',
                foreground: '#9aa1ab',
            },
            {
                token: 'operator.swift',
                foreground: '#9aa1ab',
            },
            {
                token: 'predefined.sql',
                foreground: '#8fb4ff',
            },
            {
                token: 'keyword.md',
                foreground: '#8fb4ff',
            },
            {
                token: 'keyword.md.*',
                foreground: '#8fb4ff',
            },
            {
                token: 'meta.separator.md',
                foreground: '#8a93b8',
            },
            {
                token: 'keyword.table.md.*',
                foreground: '#8a93b8',
            },
            {
                token: 'strong.md',
                foreground: '#ffd479',
            },
            {
                token: 'strong.md.*',
                foreground: '#ffd479',
            },
            {
                token: 'emphasis.md',
                foreground: '#c58bff',
            },
            {
                token: 'emphasis.md.*',
                foreground: '#c58bff',
            },
            {
                token: 'comment.md',
                foreground: '#7fe3b5',
            },
            {
                token: 'comment.md.*',
                foreground: '#7fe3b5',
            },
            {
                token: 'string.link.md',
                foreground: '#ff9d7a',
            },
            {
                token: 'string.target.md',
                foreground: '#ff9d7a',
            },
            {
                token: 'string.md',
                foreground: '#8a93b8',
            },
            {
                token: 'variable.source.md',
                foreground: '#dfe6ff',
            },
            {
                token: 'keyword.go',
                foreground: '#c58bff',
            },
            {
                token: 'keyword.go.*',
                foreground: '#c58bff',
            },
            {
                token: 'string.go',
                foreground: '#7fe3b5',
            },
            {
                token: 'comment.go',
                foreground: '#8a93b8',
            },
            {
                token: 'comment.go.*',
                foreground: '#8a93b8',
            },
            {
                token: 'number.go',
                foreground: '#ffd479',
            },
            {
                token: 'number.go.*',
                foreground: '#ffd479',
            },
            {
                token: 'delimiter.go',
                foreground: '#9aa1ab',
            },
            {
                token: 'delimiter.go.*',
                foreground: '#9aa1ab',
            },
            {
                token: 'annotation.go',
                foreground: '#ff9d7a',
            },
            {
                token: 'identifier.go',
                foreground: '#8fb4ff',
            },
            {
                token: 'keyword.type.go',
                foreground: '#5eead4',
            },
            {
                token: 'keyword.const.go',
                foreground: '#5eead4',
            },
        ],
    },
} as const;
export type GeneratedEditorThemeName = keyof typeof generatedEditorThemes;
