import { appendFile, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  buildParityAccountingReport,
  type ParityAccountingReport,
} from './accounting';
import type { CapturedParityComparison } from './evidence';

/**
 * The filesystem half of T054's accounting, kept apart from `accounting.ts` so
 * that the pure planning and classification logic stays unit-testable: Jest owns
 * `e2e/parity/**` and transforms it as CommonJS, where the `import.meta.url`
 * below is a syntax error. Only Playwright loads this module.
 */

const REPOSITORY_ROOT = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../..',
);

/**
 * Per-run scratch, under the gitignored `frontend/test-results/`. Appends are
 * line-sized and opened `O_APPEND`, so concurrent Playwright workers interleave
 * lines without corrupting one another.
 */
const CAPTURE_LOG = resolve(
  REPOSITORY_ROOT,
  'test-results/parity-accounting.jsonl',
);

/**
 * A compact top-level parity report, so it is committed: `.gitignore:38`
 * excludes the per-case subdirectories two levels below `parity/`, never its
 * top-level files. It sits beside `manifest-report.json`, which is this same
 * accounting for the withdrawn whole-screen contract and is regenerated by
 * nothing.
 */
export const ACCOUNTING_REPORT_PATH = resolve(
  REPOSITORY_ROOT,
  '../specs/003-real-files-and-tabs/evidence/ft-vs-08/parity/accounting-report.json',
);

export async function resetParityAccounting(): Promise<void> {
  await mkdir(dirname(CAPTURE_LOG), { recursive: true });
  await rm(CAPTURE_LOG, { force: true });
}

export async function recordParityCapture(
  capture: CapturedParityComparison,
): Promise<void> {
  await mkdir(dirname(CAPTURE_LOG), { recursive: true });
  await appendFile(CAPTURE_LOG, `${JSON.stringify(capture)}\n`, 'utf8');
}

export async function readRecordedCaptures(): Promise<
  readonly CapturedParityComparison[]
> {
  const raw = await readFile(CAPTURE_LOG, 'utf8').catch(() => '');
  return raw
    .split('\n')
    .filter((line) => line.trim().length > 0)
    .map((line) => JSON.parse(line) as CapturedParityComparison);
}

export async function writeParityAccountingReport(): Promise<ParityAccountingReport> {
  const report = buildParityAccountingReport(await readRecordedCaptures());
  await mkdir(dirname(ACCOUNTING_REPORT_PATH), { recursive: true });
  await writeFile(
    ACCOUNTING_REPORT_PATH,
    `${JSON.stringify(report, null, 2)}\n`,
    'utf8',
  );
  return report;
}
