// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings(arg1) {
  return window['go']['settings']['SettingsHandler']['GetSettings'](arg1);
}

export function ResetAppearance(arg1) {
  return window['go']['settings']['SettingsHandler']['ResetAppearance'](arg1);
}

export function UpdateAppearance(arg1, arg2) {
  return window['go']['settings']['SettingsHandler']['UpdateAppearance'](arg1, arg2);
}

export function UpdateContentPrivacy(arg1, arg2) {
  return window['go']['settings']['SettingsHandler']['UpdateContentPrivacy'](arg1, arg2);
}

export function UpdateEditor(arg1, arg2) {
  return window['go']['settings']['SettingsHandler']['UpdateEditor'](arg1, arg2);
}

export function UpdateFile(arg1, arg2) {
  return window['go']['settings']['SettingsHandler']['UpdateFile'](arg1, arg2);
}

export function UpdateMarkdown(arg1, arg2) {
  return window['go']['settings']['SettingsHandler']['UpdateMarkdown'](arg1, arg2);
}
