// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';
import {apperr} from '../models';

export function GetSettings(arg1:bridge.Request):Promise<apperr.SettingsResult>;

export function ResetAppearance(arg1:bridge.Request):Promise<apperr.VoidResult>;

export function UpdateAppearance(arg1:bridge.Request,arg2:apperr.AppearanceSettings):Promise<apperr.VoidResult>;

export function UpdateContentPrivacy(arg1:bridge.Request,arg2:apperr.ContentPrivacySettings):Promise<apperr.VoidResult>;

export function UpdateEditor(arg1:bridge.Request,arg2:apperr.EditorSettings):Promise<apperr.VoidResult>;

export function UpdateFile(arg1:bridge.Request,arg2:apperr.FileSettings):Promise<apperr.VoidResult>;

export function UpdateMarkdown(arg1:bridge.Request,arg2:apperr.MarkdownSettings):Promise<apperr.VoidResult>;
