// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['settings']['SettingsHandler']['GetSettings']();
}

export function ResetAppearance() {
  return window['go']['settings']['SettingsHandler']['ResetAppearance']();
}

export function UpdateAppearance(arg1) {
  return window['go']['settings']['SettingsHandler']['UpdateAppearance'](arg1);
}

export function UpdateContentPrivacy(arg1) {
  return window['go']['settings']['SettingsHandler']['UpdateContentPrivacy'](arg1);
}

export function UpdateEditor(arg1) {
  return window['go']['settings']['SettingsHandler']['UpdateEditor'](arg1);
}

export function UpdateFile(arg1) {
  return window['go']['settings']['SettingsHandler']['UpdateFile'](arg1);
}

export function UpdateMarkdown(arg1) {
  return window['go']['settings']['SettingsHandler']['UpdateMarkdown'](arg1);
}
