// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apperr} from '../models';

export function GetSettings():Promise<apperr.SettingsResult>;

export function ResetAppearance():Promise<apperr.VoidResult>;

export function UpdateAppearance(arg1:apperr.AppearanceSettings):Promise<apperr.VoidResult>;

export function UpdateContentPrivacy(arg1:apperr.ContentPrivacySettings):Promise<apperr.VoidResult>;

export function UpdateMarkdown(arg1:apperr.MarkdownSettings):Promise<apperr.VoidResult>;
